### ISSUE TITLE
Adjust speed?

### ISSUE THREAD

**Issue by doyousketch2** [kondrak/rust64#13]
Is there a way to turn clock-speed up or down?  

Turbo would be nice for blazing past some passages,  
and slowing it way down to watch program execution would be pretty smooth too.  

https://mobile.twitter.com/doyousketch2/status/892515790989258752

**Comment by kondrak** [comment]
There's no turbo mode in the same sense as in VICE or other emulators, so the only thing you can do right now is manually change the clock speed. This does sound like a nice feature though - if you feel like contributing, pull requests are welcome! :)
