### ISSUE TITLE
Panic on running "Daah, Those Acid Pills!"

### ISSUE THREAD

**Issue by xTibor** [kondrak/rust64#14]
When I run this onefiler demo from Censor Design the SID emulation code throws the following panic after a few seconds:

```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', src/c64/sid.rs:635:25
```
https://github.com/kondrak/rust64/blob/a579a3c646dd295b0ef69339cf027666b63b3d40/src/c64/sid.rs#L635

* `rustc --version`: rustc 1.21.0-nightly (a7e0d3a81 2017-08-11)
* Full backtrace: https://gist.github.com/xTibor/6e70f4df4c83d097c3f6a227a4334638
* CSDb download: http://csdb.dk/release/?id=118639

**Comment by kondrak** [comment]
Thanks for the report! Seems that I missed a wrapping sub/add in that spot, I'll fix it as soon as I get back to my computer.

**Comment by kondrak** [comment]
I just checked the demo and it seems to work fine (not counting broken sound but that's the SID emulation issue). You said it happens after few seconds - how quickly does the crash occur?

**Comment by kondrak** [comment]
Ah, forgot the check is in debug only, I see it now.

**Comment by kondrak** [comment]
Added wrapping operations where necessary in latest commits and also bumped to latest minifb.
