### ISSUE TITLE
100% CPU usage and speed issues

### ISSUE THREAD

**Issue by kondrak** [kondrak/rust64#3]
@emoon @petevine Creating an issue from the further discussion at:
https://github.com/kondrak/rust64/issues/1#issuecomment-168832065

**Comment by emoon** [comment]
Notice that your program will *always* take 100% cpu (on one thread that is) if you let it run at full speed.

**Comment by kondrak** [comment]
I'm aware of this, however it wasn't as noticeable in Windows Task Manager.

**Comment by emoon** [comment]
It will not show 100% it will show 100/<number of threads in your system> So if you have 8 threads/cores there will be one at ~13% but it should never be 100% because that would be very weird :)

**Comment by kondrak** [comment]
Correct! But it's still weird that the issue wasn't there a few months ago according to @petevine since I haven't added that much extra functionality to it.

**Comment by emoon** [comment]
Yeah. Rendering the extra window will likely add some CPU time but shouldn't be too bad (minifb on windows mostly rely on Win32 API calls to do the heavy lifting anyway)

**Comment by kondrak** [comment]
It's not bad, in current state it only adds some slight CPU usage + I don't do anything with the window once it's closed. For sake of completeness I checked without creating the window at all and CPU usage doesn't change.

**Comment by emoon** [comment]
Alright. I would expect the Win32 calls to be fairly fast so it shouldn't change too much.

**Comment by kondrak** [comment]
I'll post results from Sleepy later today, maybe it will provide something interesting to look at.

**Comment by kondrak** [comment]
I sampled the program for approximately 60 seconds (window being updated each frame) and here's the result: out of 60.33s, only 0.03s is spent on the emulation alone. I was expecting window updating taking most of the time but not at this disproportion. Interestingly I ran the same test on noise example in minifb and out of 60 seconds the update took 51, so there's quite a difference (I checked single window mode, 320x200 resolution, X1 scale in both cases for consistent results). 

![untitled](https://cloud.githubusercontent.com/assets/423295/12113334/506ef374-b3a2-11e5-806e-90683a1484fc.png)


[rust64-60sec.zip](https://github.com/kondrak/rust64/files/78301/rust64-60sec.zip)

**Comment by petevine** [comment]
I don't use windows but you seem to have that platform covered.

My recollection might be fuzzy so it's still possible it was always running at 100% - I'll let you know if I have an old binary lying around.

**Comment by petevine** [comment]
If anyone remembers the dependencies' versions (sdl2, minifb) from a month ago I'll try building from an old source tarball.

**Comment by kondrak** [comment]
It's ok, I checked myself and the problem was there from the beginning. Thanks though!

**Comment by emoon** [comment]
Wasn't there a point where the SDL update was really slow and switching to minifb made it faster?

**Comment by emoon** [comment]
Also what you can do is to use the time crate  (I use it for minifb) and measure the time which emu update + window update takes and then just have some commandline flag to print the time of each of these functions.. that timing is more accurate than sleepy and is also cross platform. There might also be some profiling lib to Rust that does the same thing.

**Comment by petevine** [comment]
Good news @emoon, I've just tested this emulator @24 bpp on ARM and it works now. I'm posting the news here cause there's no difference in CPU usage between platforms so it's not an issue with the former's `X/SDL/nvidia driver` combination.

**Comment by emoon** [comment]
@petevine cool. I will close the minifb issue then. I might in the future add 32 -> 16 bit conv if I'm bored one day :) (also can be fun to do some simd coding now and then :)

**Comment by petevine** [comment]
Ah yes, forgot to mention it - some platforms like OpenPandora only support the 16bpp depth, and due to  driver issues on Odroid C1 it's the most problem-free one here as well.  So yeah, please add it sometime :)

**Comment by emoon** [comment]
I see. I will add an issue about supporting that then. Also does those platform support NEON or some kind of simd instructions?

**Comment by petevine** [comment]
Yep, Neon is supported on all Odroids and OpenPandora (pandora is soft-float though)

**Comment by emoon** [comment]
Cool. Yeah. I wouldn't use any floats here (integer instructions only)

**Comment by kondrak** [comment]
Minifb *is* faster than SDL and is one of the reasons I stayed with it, however it never solved the issue of updating the window each frame and getting immensive lag. I didn't bother with it because I knew that the updates would only occur at specific time intervals (VBlanks) and as such it works well.

I'll play with getting the times for each function and have a closer look at this problem again, once I nail down the bug I've been hunting for a few days now. :)

**Comment by emoon** [comment]
Cool. Btw, I found this https://github.com/cmr/hprof

Just something I would want at some point and it's already there (yah!)

**Comment by kondrak** [comment]
It's (almost) always like that my friend!

**Comment by emoon** [comment]
Yeah that is one thing I really like with Rust. Very easy to to try out new stuff and good bunch of libs already :)
